import './globals.css';
import type { Metadata } from 'next';
import { classNames } from '@marulloc/components-library/utils';

import { theme } from '@/styles/theme';
import { getMenu } from '@/services/common/service';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import CartProvider from '@/components/cart/CartProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headerMenu = await getMenu('custom-storefront-menu');
  // const footerMenu = await getMenu('custom-storefront-menu');

  return (
    <html lang="en" className="h-full scroll-smooth w-screen overflow-x-hidden">
      <CartProvider>
        <body className={classNames('font-mono', '  min-h-full   ', theme.bodyBackground)}>
          <Header />

          <main className={classNames('relative   z-0 ')}>{children}</main>

          <Footer />
        </body>
      </CartProvider>
    </html>
  );
}
